CREATE TABLE IF NOT EXISTS "DWMV_FALECIDO" (
	"SK_FALECIDO" INTEGER NOT NULL UNIQUE,
	"DT_NASCIMENTO" TEXT,
	"SK_MUNICIPIO_NAT" INTEGER,
	"SK_RACA_COR" INTEGER,
	"SK_OCUPACAO" INTEGER,
	"SK_SEXO" INTEGER,
	"SK_ESTADO_CIVIL" INTEGER,
	"SK_ESCOLARIDADE" INTEGER,
	PRIMARY KEY("SK_FALECIDO"),
	FOREIGN KEY ("SK_MUNICIPIO_NAT") REFERENCES "DWCD_MUNICIPIO"("SK_MUNICIPIO")
	ON UPDATE NO ACTION ON DELETE NO ACTION,
	FOREIGN KEY ("SK_RACA_COR") REFERENCES "DWCD_RACA_COR"("SK_RACA_COR")
	ON UPDATE NO ACTION ON DELETE NO ACTION,
	FOREIGN KEY ("SK_OCUPACAO") REFERENCES "DWCD_OCUPACAO"("SK_OCUPACAO")
	ON UPDATE NO ACTION ON DELETE NO ACTION,
	FOREIGN KEY ("SK_ESCOLARIDADE") REFERENCES "DWCD_ESCOLARIDADE"("SK_ESCOLARIDADE")
	ON UPDATE NO ACTION ON DELETE NO ACTION
);

CREATE TABLE IF NOT EXISTS "DWCD_SEXO" (
	"SK_SEXO" INTEGER NOT NULL UNIQUE,
	"DS_SEXO" TEXT,
	PRIMARY KEY("SK_SEXO"),
	FOREIGN KEY ("SK_SEXO") REFERENCES "DWMV_FALECIDO"("SK_SEXO")
	ON UPDATE NO ACTION ON DELETE NO ACTION
);

CREATE TABLE IF NOT EXISTS "DWCD_ESTADO_CIVIL" (
	"SK_ESTADO_CIVIL" INTEGER NOT NULL UNIQUE,
	"DS_ESTADO_CIVIL" TEXT,
	PRIMARY KEY("SK_ESTADO_CIVIL"),
	FOREIGN KEY ("SK_ESTADO_CIVIL") REFERENCES "DWMV_FALECIDO"("SK_ESTADO_CIVIL")
	ON UPDATE NO ACTION ON DELETE NO ACTION
);

CREATE TABLE IF NOT EXISTS "DWCD_ESCOLARIDADE" (
	"SK_ESCOLARIDADE" INTEGER NOT NULL UNIQUE,
	"DS_ESCOLARIDADE" TEXT,
	PRIMARY KEY("SK_ESCOLARIDADE"),
	FOREIGN KEY ("SK_ESCOLARIDADE") REFERENCES "DWMV_MAE_FALECIDO"("SK_ESCOLARIDADE")
	ON UPDATE NO ACTION ON DELETE NO ACTION
);

CREATE INDEX IF NOT EXISTS "DWCD_ESCOLARIDADE_index_0"
ON "DWCD_ESCOLARIDADE" ();
CREATE TABLE IF NOT EXISTS "DWCD_OCUPACAO" (
	"SK_OCUPACAO" INTEGER NOT NULL UNIQUE,
	"CD_CBO" INTEGER,
	"DS_OCUPACAO" TEXT,
	PRIMARY KEY("SK_OCUPACAO"),
	FOREIGN KEY ("SK_OCUPACAO") REFERENCES "DWMV_MAE_FALECIDO"("SK_OCUPACAO")
	ON UPDATE NO ACTION ON DELETE NO ACTION
);

CREATE TABLE IF NOT EXISTS "DWCD_RACA_COR" (
	"SK_RACA_COR" INTEGER NOT NULL UNIQUE,
	"DS_RACA_COR" TEXT,
	PRIMARY KEY("SK_RACA_COR")
);

CREATE TABLE IF NOT EXISTS "DWCD_MUNICIPIO" (
	"SK_MUNICIPIO" INTEGER NOT NULL UNIQUE,
	"CD_MUNICIPIO" INTEGER,
	"NM_MUNICIPIO" TEXT,
	"CD_UF" TEXT,
	PRIMARY KEY("SK_MUNICIPIO")
);

CREATE TABLE IF NOT EXISTS "DWMV_MAE_FALECIDO" (
	"SK_MAE_FALECIDO" INTEGER NOT NULL UNIQUE,
	"QT_IDADE" INTEGER,
	"SK_ESCOLARIDADE" INTEGER,
	"SK_OCUPACAO" INTEGER,
	"QT_FILHOS_VIVOS" INTEGER,
	"QT_FILHOS_MORTOS" INTEGER,
	PRIMARY KEY("SK_MAE_FALECIDO")
);
