CREATE TABLE IF NOT EXISTS "DWCD_FALECIDO" (
	"SK_FALECIDO" INTEGER NOT NULL UNIQUE,
	"DT_NASCIMENTO" TEXT,
	"IDADE" INTEGER,
	"SK_TIPO_IDADE" INTEGER,
	"SK_MUNICIPIO_NAT" INTEGER,
	"SK_MUNICIPIO_RESIDENCIA" INTEGER,
	"SK_RACA_COR" INTEGER,
	"SK_OCUPACAO" INTEGER,
	"SK_SEXO" INTEGER,
	"SK_ESTADO_CIVIL" INTEGER,
	"SK_ESCOLARIDADE" INTEGER,
	"DT_CARGA" TEXT,
	PRIMARY KEY("SK_FALECIDO"),
	FOREIGN KEY ("SK_MUNICIPIO_NAT") REFERENCES "DWCD_MUNICIPIO"("SK_MUNICIPIO")
	ON UPDATE NO ACTION ON DELETE NO ACTION,
	FOREIGN KEY ("SK_RACA_COR") REFERENCES "DWCD_RACA_COR"("SK_RACA_COR")
	ON UPDATE NO ACTION ON DELETE NO ACTION,
	FOREIGN KEY ("SK_OCUPACAO") REFERENCES "DWCD_OCUPACAO"("SK_OCUPACAO")
	ON UPDATE NO ACTION ON DELETE NO ACTION,
	FOREIGN KEY ("SK_ESCOLARIDADE") REFERENCES "DWCD_ESCOLARIDADE"("SK_ESCOLARIDADE")
	ON UPDATE NO ACTION ON DELETE NO ACTION,
	FOREIGN KEY ("SK_MUNICIPIO_RESIDENCIA") REFERENCES "DWCD_MUNICIPIO"("SK_MUNICIPIO")
	ON UPDATE NO ACTION ON DELETE NO ACTION,
	FOREIGN KEY ("SK_TIPO_IDADE") REFERENCES "DWCD_TIPO_IDADE"("SK_TIPO_IDADE")
	ON UPDATE NO ACTION ON DELETE NO ACTION
);

CREATE TABLE IF NOT EXISTS "DWCD_SEXO" (
	"SK_SEXO" INTEGER NOT NULL UNIQUE,
	"CD_SEXO" INTEGER,
	"DS_SEXO" TEXT,
	"ST_SITUACAO" TEXT,
	"DT_CARGA" TEXT,
	PRIMARY KEY("SK_SEXO"),
	FOREIGN KEY ("SK_SEXO") REFERENCES "DWCD_FALECIDO"("SK_SEXO")
	ON UPDATE NO ACTION ON DELETE NO ACTION
);

CREATE TABLE IF NOT EXISTS "DWCD_ESTADO_CIVIL" (
	"SK_ESTADO_CIVIL" INTEGER NOT NULL UNIQUE,
	"CD_ESTADO_CIVIL" INTEGER,
	"DS_ESTADO_CIVIL" TEXT,
	"ST_SITUACAO" TEXT,
	"DT_CARGA" TEXT,
	PRIMARY KEY("SK_ESTADO_CIVIL"),
	FOREIGN KEY ("SK_ESTADO_CIVIL") REFERENCES "DWCD_FALECIDO"("SK_ESTADO_CIVIL")
	ON UPDATE NO ACTION ON DELETE NO ACTION
);

CREATE TABLE IF NOT EXISTS "DWCD_ESCOLARIDADE" (
	"SK_ESCOLARIDADE" INTEGER NOT NULL UNIQUE,
	"CD_ESCOLARIDADE" INTEGER,
	"DS_ESCOLARIDADE" TEXT,
	"ST_SITUACAO" TEXT,
	"DT_CARGA" TEXT,
	PRIMARY KEY("SK_ESCOLARIDADE")
);

CREATE TABLE IF NOT EXISTS "DWCD_OCUPACAO" (
	"SK_OCUPACAO" INTEGER NOT NULL UNIQUE,
	"CD_CBO" INTEGER,
	"DS_OCUPACAO" TEXT,
	"ST_SITUACAO" TEXT,
	"DT_CARGA" TEXT,
	PRIMARY KEY("SK_OCUPACAO")
);

CREATE TABLE IF NOT EXISTS "DWCD_RACA_COR" (
	"SK_RACA_COR" INTEGER NOT NULL UNIQUE,
	"CD_RACA_COR" INTEGER,
	"DS_RACA_COR" TEXT,
	"ST_SITUACAO" TEXT,
	"DT_CARGA" TEXT,
	PRIMARY KEY("SK_RACA_COR")
);

CREATE TABLE IF NOT EXISTS "DWCD_MUNICIPIO" (
	"SK_MUNICIPIO" INTEGER NOT NULL UNIQUE,
	"CD_MUNICIPIO" INTEGER,
	"NM_MUNICIPIO" TEXT,
	"CD_UF" TEXT,
	"ST_SITUACAO" TEXT,
	"DT_CARGA" TEXT,
	PRIMARY KEY("SK_MUNICIPIO"),
	FOREIGN KEY ("SK_MUNICIPIO") REFERENCES "DWMV_OBITO"("SK_MUNICIPIO_OBITO")
	ON UPDATE NO ACTION ON DELETE NO ACTION
);

CREATE TABLE IF NOT EXISTS "DWMV_OBITO" (
	"SK_OBITO" INTEGER NOT NULL UNIQUE,
	"DT_OBITO" TEXT,
	"DT_ATESTADO" TEXT,
	"CD_ESTABELECIMENTO_SAUDE" INTEGER,
	"ST_ASSISTENCIA_MEDICA" TEXT,
	"ST_INVESTIGADO" TEXT,
	"ST_EPIDEMIA" TEXT,
	"SK_MUNICIPIO_OBITO" INTEGER,
	"SK_TIPO_OBITO" INTEGER,
	"SK_LOCAL_OBITO" INTEGER,
	"DT_CARGA" TEXT,
	PRIMARY KEY("SK_OBITO"),
	FOREIGN KEY ("SK_OBITO") REFERENCES "DWMV_REL_OBITO_CAUSA"("SK_OBITO")
	ON UPDATE NO ACTION ON DELETE NO ACTION
);

CREATE TABLE IF NOT EXISTS "DWCD_LOCAL_OBITO" (
	"SK_LOCAL_OBITO" INTEGER NOT NULL UNIQUE,
	"CD_LOCAL_OBITO" INTEGER,
	"DS_LOCAL_OBITO" TEXT,
	"ST_SITUACAO" TEXT,
	"DT_CARGA" TEXT,
	PRIMARY KEY("SK_LOCAL_OBITO"),
	FOREIGN KEY ("SK_LOCAL_OBITO") REFERENCES "DWMV_OBITO"("SK_LOCAL_OBITO")
	ON UPDATE NO ACTION ON DELETE NO ACTION
);

CREATE TABLE IF NOT EXISTS "DWCD_DOENÇA" (
	"SK_DOENÇA" INTEGER,
	"CD_CID" TEXT NOT NULL UNIQUE,
	"ST_SITUACAO" TEXT,
	"DT_CARGA" TEXT,
	PRIMARY KEY("CD_CID"),
	FOREIGN KEY ("SK_DOENÇA") REFERENCES "DWMV_REL_OBITO_CAUSA"("SK_DOENCA")
	ON UPDATE NO ACTION ON DELETE NO ACTION
);

CREATE TABLE IF NOT EXISTS "DWCD_TIPO_CAUSA" (
	"SK_TIPO_CAUSA" INTEGER NOT NULL UNIQUE,
	"DS_TIPO_CAUSA" TEXT,
	"ST_SITUACAO" TEXT,
	"DT_CARGA" TEXT,
	PRIMARY KEY("SK_TIPO_CAUSA"),
	FOREIGN KEY ("SK_TIPO_CAUSA") REFERENCES "DWMV_REL_OBITO_CAUSA"("SK_TIPO_CAUSA")
	ON UPDATE NO ACTION ON DELETE NO ACTION
);

CREATE TABLE IF NOT EXISTS "DWCD_TIPO_OBT_NAO_NATURAL" (
	"SK_TIPO_OBT" INTEGER NOT NULL UNIQUE,
	"CD_TIPO_OBT" INTEGER,
	"DS_TIPO_OBITO" TEXT,
	"ST_SITUACAO" TEXT,
	"DT_CARGA" TEXT,
	PRIMARY KEY("SK_TIPO_OBT"),
	FOREIGN KEY ("SK_TIPO_OBT") REFERENCES "DWMV_OBITO"("SK_TIPO_OBITO")
	ON UPDATE NO ACTION ON DELETE NO ACTION
);

CREATE TABLE IF NOT EXISTS "DWCD_TIPO_IDADE" (
	"SK_TIPO_IDADE" INTEGER NOT NULL UNIQUE,
	"CD_TIPO_IDADE" INTEGER,
	"DS_TIPO_IDADE" TEXT,
	"ST_SITUACAO" TEXT,
	"DT_CARGA" TEXT,
	PRIMARY KEY("SK_TIPO_IDADE")
);

CREATE TABLE IF NOT EXISTS "DWMV_REL_OBITO_CAUSA" (
	"SK_REL_OBITO_CAUSA" INTEGER NOT NULL UNIQUE,
	"SK_TIPO_CAUSA" INTEGER,
	"SK_DOENCA" INTEGER,
	"SK_OBITO" INTEGER,
	"DT_CARGA" TEXT,
	PRIMARY KEY("SK_REL_OBITO_CAUSA")
);
